substitutions:
  device_name: modbus-spy-new-sw-dev
  friendly_name: Modbus Spy New SW Dev
  time_timezone: "Europe/Amsterdam"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
    #   type: git
    #   url: https://github.com/pdjong/daalderop-esphome
    #   ref: main
    # refresh: 0s
      type: local
      path: components
    
# Enable logging
logger:
  # baud_rate: 115200
  level: INFO
  #logs:
    #sensor: INFO
    #ModbusSpy: WARN
# Enable Home Assistant API
api:
  encryption:
    key: "DYWW/4NFHUUChW2rbGIhJv7MME2MqROqOHKF4WblPHk="
ota:
  password: "e5264b2500ef5b812b82d4342c5a60f6"

wifi:
  ssid: ?
  password: ?
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HeatPumpController"
    password: "heatpump"

captive_portal:

# Status LED of ESP
status_led:
  pin: 
    number: 33

uart:
  baud_rate: 19200
  rx_pin: 32
  parity: ODD

modbus_spy:
  id: modbusspy
  
sensor:
  - platform: modbus_spy
    name: "Inside Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x0B
    register_address: 41200
    filters:
      - offset: -3000
      - multiply: .01
  - platform: modbus_spy
    name: "Sanitary Hot Water Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x0B
    register_address: 41201
    filters:
      - offset: -3000
      - multiply: .01  
  - platform: modbus_spy
    name: "Heating/Cooling Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x0B
    register_address: 41202
    filters:
      - offset: -3000
      - multiply: .01     
  - platform: modbus_spy
    name: "Heat Exchanger Water Outlet Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x0B
    register_address: 41203
    filters:
      - offset: -3000
      - multiply: .01          
  - platform: modbus_spy
    name: "Heat Exchanger Water Inlet Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x0B
    register_address: 41204
    filters:
      - offset: -3000
      - multiply: .01                        
  - platform: modbus_spy
    name: "Indoor Coil Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x0B
    register_address: 41205
    filters:
      - offset: -3000
      - multiply: .01                        
  - platform: modbus_spy
    name: "Heating/Cooling Circuit 1 Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x0B
    register_address: 41205
    filters:
      - offset: -3000
      - multiply: .01
  - platform: modbus_spy
    name: "Outdoor Voltage"
    device_class: "voltage"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "V"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42101
  - platform: modbus_spy
    name: "Outdoor Current"
    device_class: "current"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "A"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42102
    filters:
      - multiply: .1
  - platform: modbus_spy
    name: "Compressor Working Speed Setpoint"
    device_class: "frequency"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "Hz"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42103
  - platform: modbus_spy
    name: "Compressor Working Speed Actual"
    device_class: "frequency"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "Hz"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42104
  - platform: modbus_spy
    name: "Outdoor Fan Setpoint"
    device_class: "frequency"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "rpm"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42105
  - platform: modbus_spy
    name: "Outdoor Fan 1 Actual"
    device_class: "frequency"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "rpm"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42106
  - platform: modbus_spy
    name: "Outside Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42111
    filters:
      - offset: -3000
      - multiply: .01
  - platform: modbus_spy
    name: "Outdoor Coil Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42112
    filters:
      - offset: -3000
      - multiply: .01
  - platform: modbus_spy
    name: "Discharge Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42113
    filters:
      - offset: -3000
      - multiply: .01       
  - platform: modbus_spy
    name: "Suction Temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42114
    filters:
      - offset: -3000
      - multiply: .01 

  - platform: modbus_spy
    name: "Low Pressure"
    device_class: "pressure"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "bar"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42117
    filters:
      - multiply: .1    
  - platform: modbus_spy
    name: "High Pressure"
    device_class: "pressure"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "bar"
    #icon: "mdi:thermometer"    
    device_address: 0x02
    register_address: 42118
    filters:
      - multiply: .1   

  - platform: debug
    free:
      name: Heap Free
    loop_time:
      name: Loop Time

  - platform: uptime
    id: sensor_uptime
  - platform: template
    id: sensor_uptime_timestamp
    name: "Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state
      );
      return timestamp;
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "Modbus Spy WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 20s
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Modbus Spy WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"

binary_sensor:
  - platform: modbus_spy
    name: "Heating Switch - Room Thermostat"
    device_address: 0x0B
    register_address: 41215

# binary_sensor:
#   - platform: template
#     name: modbus_spy_defrost
#     lambda: |-
#       return (id(decode20).state == 68 && (id(decode24).state == 1 || id(decode25).state == 2048)) || (id(decode20).state == 4);
              

time:
  - platform: homeassistant
    id: time_homeassistant
    timezone: "Europe/Amsterdam"
    on_time_sync:
      - component.update: sensor_uptime_timestamp      

# text_sensor:
#   - platform: template
#     id: three_way_valve_text
#     name: modbus_spy_three_way_valve_text

debug:
  update_interval: 5s

web_server:
  port: 80